const crypto=require('crypto');
const express=require('express');
const pool=require('../db');
const {validateEvidenceMetadata,validateCitations,assessReview}=require('../services/diligencePolicy');

module.exports=function createGovernedDiligenceRouter(){
  const router=express.Router(); const makeId=()=>crypto.randomUUID();
  const respondError=(res,error)=>res.status(error.status||(error.code==='23505'?409:400)).json({error:error.code==='23505'?'Duplicate matter mutation':error.message});
  async function member(req,roles){const workspaceId=req.params.workspaceId||req.body.workspaceId;const result=await pool.query('SELECT role FROM diligence_memberships WHERE workspace_id=$1 AND user_id=$2',[workspaceId,req.user.id]);if(!result.rows[0]||(roles&&!roles.includes(result.rows[0].role))){const error=new Error('Matter workspace role is not authorized');error.status=403;throw error;}return{workspaceId,role:result.rows[0].role};}
  async function matterExists(matterId,workspaceId){const result=await pool.query('SELECT * FROM diligence_matters WHERE id=$1 AND workspace_id=$2',[matterId,workspaceId]);return result.rows[0];}

  router.post('/workspaces',async(req,res)=>{try{if(!['admin','partner'].includes(req.user.role))return res.status(403).json({error:'Partner or administrator role is required'});const name=String(req.body.name||'').trim();if(name.length<3)throw new Error('name must contain at least 3 characters');const workspaceId=makeId();const client=await pool.connect();try{await client.query('BEGIN');await client.query('INSERT INTO diligence_workspaces(id,name,created_by) VALUES($1,$2,$3)',[workspaceId,name,req.user.id]);await client.query("INSERT INTO diligence_memberships(workspace_id,user_id,role) VALUES($1,$2,'matter_partner')",[workspaceId,req.user.id]);await client.query("INSERT INTO diligence_audit_events(workspace_id,actor_user_id,action,entity_type,entity_id) VALUES($1,$2,'workspace.created','workspace',$1)",[workspaceId,req.user.id]);await client.query('COMMIT');}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}res.status(201).json({id:workspaceId,name,role:'matter_partner'});}catch(error){respondError(res,error);}});
  router.post('/workspaces/:workspaceId/members',async(req,res)=>{try{const{workspaceId}=await member(req,['matter_partner']);const role=String(req.body.role||'');if(!['reviewer','analyst','viewer'].includes(role)||!Number.isInteger(Number(req.body.userId)))throw new Error('valid userId and role are required');await pool.query(`INSERT INTO diligence_memberships(workspace_id,user_id,role) VALUES($1,$2,$3) ON CONFLICT(workspace_id,user_id) DO UPDATE SET role=EXCLUDED.role`,[workspaceId,req.body.userId,role]);res.status(201).json({workspaceId,userId:Number(req.body.userId),role});}catch(error){respondError(res,error);}});
  router.post('/workspaces/:workspaceId/matters',async(req,res)=>{try{const{workspaceId}=await member(req,['matter_partner','reviewer']);const{name,matterReference,authorizationBasis,retentionUntil}=req.body;if(!name||!matterReference||String(authorizationBasis||'').trim().length<10)throw new Error('name, matterReference, and specific authorizationBasis are required');const matterId=makeId();await pool.query(`INSERT INTO diligence_matters(id,workspace_id,name,matter_reference,authorization_basis,retention_until,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)`,[matterId,workspaceId,name,matterReference,authorizationBasis,retentionUntil||null,req.user.id]);res.status(201).json({id:matterId,status:'intake'});}catch(error){respondError(res,error);}});
  router.post('/workspaces/:workspaceId/matters/:matterId/evidence',async(req,res)=>{try{const{workspaceId}=await member(req,['matter_partner','reviewer','analyst']);if(!await matterExists(req.params.matterId,workspaceId))return res.status(404).json({error:'Matter not found'});validateEvidenceMetadata(req.body);const evidenceId=makeId();await pool.query(`INSERT INTO diligence_evidence(id,matter_id,workspace_id,storage_ref,sha256,source_name,source_uri,authorization_basis,received_at,source_effective_date,classification,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,[evidenceId,req.params.matterId,workspaceId,req.body.storageRef,req.body.sha256.toLowerCase(),req.body.sourceName,req.body.sourceUri||null,req.body.authorizationBasis,req.body.receivedAt,req.body.sourceEffectiveDate||null,req.body.classification,req.user.id]);res.status(201).json({id:evidenceId,processingStatus:'registered',contentAccepted:false});}catch(error){respondError(res,error);}});
  router.post('/workspaces/:workspaceId/matters/:matterId/claims',async(req,res)=>{try{const{workspaceId}=await member(req,['matter_partner','reviewer','analyst']);const citations=validateCitations(req.body.citations);const documentIds=[...new Set(citations.map(c=>c.documentId))];const evidence=await pool.query('SELECT id FROM diligence_evidence WHERE matter_id=$1 AND workspace_id=$2 AND id=ANY($3::uuid[])',[req.params.matterId,workspaceId,documentIds]);if(evidence.rows.length!==documentIds.length)throw new Error('Every citation must reference evidence in this matter');if(!req.body.entityKey||!req.body.claimKey||req.body.claimValue===undefined)throw new Error('entityKey, claimKey, and claimValue are required');const claimId=makeId();await pool.query(`INSERT INTO diligence_claims(id,matter_id,workspace_id,entity_key,claim_key,claim_value,citations,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[claimId,req.params.matterId,workspaceId,req.body.entityKey,req.body.claimKey,req.body.claimValue,citations,req.user.id]);res.status(201).json({id:claimId,status:'unreviewed',citationCount:citations.length});}catch(error){respondError(res,error);}});
  router.post('/workspaces/:workspaceId/matters/:matterId/requests',async(req,res)=>{try{const{workspaceId}=await member(req,['matter_partner','reviewer','analyst']);if(!await matterExists(req.params.matterId,workspaceId))return res.status(404).json({error:'Matter not found'});if(!req.body.requestKey||!req.body.description)throw new Error('requestKey and description are required');const requestId=makeId();await pool.query(`INSERT INTO diligence_requests(id,matter_id,workspace_id,request_key,description,owner,due_date,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[requestId,req.params.matterId,workspaceId,req.body.requestKey,req.body.description,req.body.owner||null,req.body.dueDate||null,req.user.id]);res.status(201).json({id:requestId,status:'open'});}catch(error){respondError(res,error);}});
  router.post('/workspaces/:workspaceId/requests/:requestId/exception',async(req,res)=>{try{const{workspaceId}=await member(req,['matter_partner']);if(String(req.body.reason||'').trim().length<12)throw new Error('A meaningful exception reason is required');const result=await pool.query("UPDATE diligence_requests SET status='exception',exception_reason=$1,approved_by=$2 WHERE id=$3 AND workspace_id=$4 AND status IN ('open','received') RETURNING *",[req.body.reason,req.user.id,req.params.requestId,workspaceId]);if(!result.rows[0])return res.status(409).json({error:'Request cannot receive an exception'});res.json(result.rows[0]);}catch(error){respondError(res,error);}});
  router.get('/workspaces/:workspaceId/matters/:matterId/readiness',async(req,res)=>{try{const{workspaceId}=await member(req);const [claims,requests]=await Promise.all([pool.query('SELECT entity_key AS "entityKey",claim_key AS "claimKey",claim_value AS "claimValue",citations FROM diligence_claims WHERE matter_id=$1 AND workspace_id=$2 AND status<>\'superseded\'',[req.params.matterId,workspaceId]),pool.query('SELECT status FROM diligence_requests WHERE matter_id=$1 AND workspace_id=$2',[req.params.matterId,workspaceId])]);res.json(assessReview(claims.rows,requests.rows));}catch(error){respondError(res,error);}});
  router.post('/workspaces/:workspaceId/matters/:matterId/signoff',async(req,res)=>{try{const{workspaceId}=await member(req,['matter_partner']);if(!await matterExists(req.params.matterId,workspaceId))return res.status(404).json({error:'Matter not found'});const [claims,requests]=await Promise.all([pool.query('SELECT entity_key AS "entityKey",claim_key AS "claimKey",claim_value AS "claimValue",citations FROM diligence_claims WHERE matter_id=$1 AND workspace_id=$2 AND status<>\'superseded\'',[req.params.matterId,workspaceId]),pool.query('SELECT status FROM diligence_requests WHERE matter_id=$1 AND workspace_id=$2',[req.params.matterId,workspaceId])]);const readiness=assessReview(claims.rows,requests.rows);if(!readiness.readyForSignoff&&req.body.decision!=='insufficient_evidence')return res.status(409).json({error:'Matter is not ready for substantive sign-off',readiness});if(!['proceed','proceed_with_conditions','do_not_proceed','insufficient_evidence'].includes(req.body.decision)||String(req.body.rationale||'').trim().length<20)throw new Error('valid decision and substantive rationale are required');const decisionId=makeId();const client=await pool.connect();try{await client.query('BEGIN');await client.query(`INSERT INTO diligence_decisions(id,matter_id,workspace_id,decision,rationale,conditions,signed_off_by) VALUES($1,$2,$3,$4,$5,$6,$7)`,[decisionId,req.params.matterId,workspaceId,req.body.decision,req.body.rationale,req.body.conditions||[],req.user.id]);await client.query("UPDATE diligence_matters SET status='signed_off' WHERE id=$1 AND workspace_id=$2",[req.params.matterId,workspaceId]);await client.query("INSERT INTO diligence_audit_events(workspace_id,actor_user_id,action,entity_type,entity_id,reason,metadata) VALUES($1,$2,'matter.signed_off','matter',$3,$4,$5)",[workspaceId,req.user.id,req.params.matterId,req.body.rationale,{decision:req.body.decision,readiness}]);await client.query('COMMIT');}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}res.status(201).json({id:decisionId,decision:req.body.decision,professionalSignoff:true,readiness});}catch(error){respondError(res,error);}});
  return router;
};
